"""empty message

Revision ID: 8d162175374c
Revises: 162e53765211
Create Date: 2021-09-03 16:50:21.267089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d162175374c'
down_revision = '162e53765211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=250), nullable=True))
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
